"use client";

import NavBar from "./NavBar";
import Breadcrumbs from "./Breadcrumbs";
import { motion, AnimatePresence } from "framer-motion";
import Reveal from "./Reveal";
import Image from "next/image";
import {
  DollarSign,
  CreditCard,
  BarChart,
  X,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import { useMemo, useState } from "react";
import usa from "@svg-maps/usa";
import AwardsSection from "./AwardsSection";
import Footer from "./Footer";
import Link from "next/link";
import locationData from "../data/spavia-locations.json";

interface SpaviaLocation {
  id: string;
  name: string;
  brand: string;
  status: string;
  address: string;
  city: string;
  state: string;
  stateName: string;
  zip: string;
  phone: string;
  website: string;
  lat: number;
  lon: number;
  x: number | null;
  y: number | null;
}
// Generated by scripts/sync-locations.mjs from Spavia's corporate store
// locator. Re-run that script to refresh; never edit the JSON by hand.
const spaviaLocations = (locationData.locations as SpaviaLocation[]).filter(
  (loc) => loc.brand === "spavia"
);
const locationCounts = locationData.counts;

const financials = [
  { label: "Net Worth", value: "$500,000", icon: DollarSign },
  { label: "Liquid Capital", value: "$200,000", icon: CreditCard },
  {
    label: "Estimated Initial Investment*",
    value: "$479,450 – $885,450",
    icon: BarChart,
  },
];

const limitedMarkets = [
  "Colorado",
  "North Dakota",
  "South Dakota",
  "Alaska",
  "Hawaii",
  "Maryland",
  "New Jersey",
  "Rhode Island",
];

// 6 images designed for a 3-col bento: [1 is the hero (2x2)]
const galleryImages = [
  { src: "/media/front-desk-wide.webp", alt: "Spavia front desk welcome area" },
  { src: "/media/treatment-room-moody.webp", alt: "Spavia treatment room with ambient lighting" },
  { src: "/media/retreat-leather-chair.webp", alt: "Spavia Retreat Room with leather chair" },
  { src: "/media/spa-boutique-shelves.webp", alt: "Spavia Spa Boutique retail shelves" },
  { src: "/media/couples-treatment-room.webp", alt: "Spavia couples treatment room" },
  { src: "/media/fireplace-deer-mantle.webp", alt: "Spavia Retreat Room fireplace" },
];

const yourSpaviaFaqs = [
  {
    question: "What are the financial requirements to open a Spavia franchise?",
    answer:
      "Spavia recommends a minimum net worth of $500,000 and liquid capital of $200,000. The total estimated initial investment ranges from $479,450 to $885,450, per the 2026 FDD, Item 7. This includes the franchise fee, training fee, build-out, equipment, signage, technology, and three months of additional funds.",
  },
  {
    question: "How does Spavia generate recurring revenue?",
    answer:
      "Recurring revenue is the cornerstone of the Spavia model. Membership accounts for over 50% of revenue with a fiercely loyal following. Additional revenue comes from multiple streams including massage, skin care, retail, body treatments, beauty services, and gift cards.",
  },
  {
    question: "How big is the spa and wellness industry?",
    answer:
      "The global wellness market is expected to reach $8.5 trillion by 2027, with 22% of wellness growth attributed to the spa segment. The global day spa market is expected to reach $57 billion by 2033.",
  },
  {
    question: "How does Spavia help with finding a location?",
    answer:
      "Finding a great location for your Spavia requires collaboration between the franchise partner, Spavia National, and their real estate partner, JLL. This partnership ensures you find the right site for your market.",
  },
  {
    question: "Which markets are available for Spavia franchise development?",
    answer:
      "Spavia is available in most U.S. states. Limited markets include Colorado, North Dakota, South Dakota, Alaska, Hawaii, Maryland, New Jersey, and Rhode Island. Click on the interactive map above for territory details.",
  },
  {
    question: "How many Spavia locations are there?",
    answer: `There are ${locationCounts.open} Spavia locations open across ${locationCounts.states} states, with ${locationCounts.comingSoon} more opening soon. The full list is above, and each spa is independently owned and operated by a Spavia franchise partner.`,
  },
];

interface Location {
  id: string;
  name?: string;
  path: string;
}



export default function YourSpaviaContent() {
  const [hoveredState, setHoveredState] = useState<string | null>(null);
  const [selectedState, setSelectedState] = useState<string | null>(null);
  const [hoveredLocation, setHoveredLocation] = useState<SpaviaLocation | null>(
    null
  );
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(null);

  const limitedSet = useMemo(() => new Set(limitedMarkets), []);

  // Spavias grouped by state name, so both the map dialog and the directory
  // below can look a state up by the same key the SVG map uses.
  const byStateName = useMemo(() => {
    const groups = new Map<string, SpaviaLocation[]>();
    for (const loc of spaviaLocations) {
      const list = groups.get(loc.stateName) ?? [];
      list.push(loc);
      groups.set(loc.stateName, list);
    }
    return groups;
  }, []);

  // Coming-soon markers draw first so that where two spas sit almost on top of
  // each other (Cary/Raleigh, the Denver cluster) the open one stays visible.
  const plottable = useMemo(
    () =>
      spaviaLocations
        .filter((loc) => loc.x !== null && loc.y !== null)
        .sort((a, b) =>
          a.status === b.status ? 0 : a.status === "coming-soon" ? -1 : 1
        ),
    []
  );

  const selectedLocations = selectedState
    ? byStateName.get(selectedState) ?? []
    : [];
  const gold = "#C2A878";
  const limited = "#e5e5e5";
  const hover = "#000000";

  const nextImage = () => {
    setCurrentImageIndex((prev) => (prev + 1) % galleryImages.length);
  };

  const prevImage = () => {
    setCurrentImageIndex(
      (prev) => (prev - 1 + galleryImages.length) % galleryImages.length
    );
  };

  return (
    <main className="text-gray-900">
      <NavBar />
        <Breadcrumbs items={[{ label: "Your Spavia" }]} />

      {/* Hero with Video */}
      <section className="relative overflow-hidden min-h-[60svh] flex items-center justify-center py-20 text-center text-white px-6">
        {/* Background video */}
        <video
          autoPlay
          loop
          muted
          playsInline
          className="absolute inset-0 w-full h-full object-cover"
        >
          <source src="/hero-bg.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        {/* Dark overlay */}
        <div className="absolute inset-0 bg-black opacity-40"></div>

        <div className="relative z-10">
          <Reveal>
            <h1 className="text-5xl font-bold mb-6">Your Spavia</h1>
          </Reveal>

          <Reveal delay={300}>
            <h2 className="max-w-3xl mx-auto text-xl sm:text-2xl md:text-3xl font-semibold leading-relaxed">
              Financial Success Through Wellness
            </h2>
          </Reveal>

          <Reveal delay={450}>
            <p className="max-w-3xl mx-auto text-lg leading-relaxed mt-4">
              At Spavia, your investment goes beyond profitability. It’s about
              bringing an oasis of relaxation and rejuvenation to your community.
            </p>
          </Reveal>
        </div>
      </section>

      {/* Financial Requirements */}
      <section className="py-20 bg-white">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center mb-12">
            Financial Requirements
          </h2>
        </div>
        <div className="max-w-5xl mx-auto px-6 grid md:grid-cols-3 gap-6 items-stretch">
          {financials.map((item, i) => {
            const Icon = item.icon;
            return (
              <Reveal key={i} delay={i * 100} className="h-full">
                <div className="group h-full flex flex-col items-center justify-center text-center px-8 py-12 rounded-2xl border border-[#C2A878]/25 bg-[#faf7f2] shadow-[0_2px_20px_rgba(0,0,0,0.04)] hover:shadow-[0_10px_34px_rgba(194,168,120,0.20)] hover:-translate-y-1 transition-all duration-300">
                  <div className="mb-6 flex h-14 w-14 items-center justify-center rounded-full bg-[#C2A878]/12 ring-1 ring-[#C2A878]/30">
                    <Icon className="w-6 h-6 text-[#C2A878]" />
                  </div>
                  <p className="text-3xl font-bold text-gray-900 mb-3 leading-tight font-[family-name:var(--font-recoleta)]">
                    {item.value}
                  </p>
                  <p className="text-[11px] uppercase tracking-[0.2em] text-[#9c814f] font-semibold">
                    {item.label}
                  </p>
                </div>
              </Reveal>
            );
          })}
        </div>
        <p className="max-w-6xl mx-auto px-6 mt-6 text-xs text-gray-500 text-center">
          *Source: 2026 Spavia Franchise Disclosure Document, Item 7. Results vary by location.
        </p>
      </section>

      {/* Economics */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-6xl mx-auto px-6 grid md:grid-cols-3 gap-12">
          <div>
            <h3 className="text-xl font-semibold mb-4 text-[#C2A878]">
              Recurring Revenue
            </h3>
            <p>
              Recurring revenue is the cornerstone of a financially successful
              franchise. Membership accounts for over 50% of revenue with a
              fiercely loyal following.
            </p>
          </div>
          <div>
            <h3 className="text-xl font-semibold mb-4 text-[#C2A878]">
              Diversity of Revenue
            </h3>
            <p>
              Revenue generated from multiple streams: massage, skin care,
              retail, body treatments, beauty, and gift cards.
            </p>
          </div>
          <div>
            <h3 className="text-xl font-semibold mb-4 text-[#C2A878]">
              Advanced Pricing Strategy
            </h3>
            <p>
              Financial modeling maximizes revenue through yield management,
              market tiers, and membership tiers.
            </p>
          </div>
        </div>
      </section>

      {/* Industry Size */}
      <section className="py-20 bg-white">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold mb-6">Spa Industry Size</h2>
          <ul className="space-y-3 text-lg">
            <li>
              Wellness is on the rise. Global wellness market expected to reach{" "}
              <span className="font-semibold">$8.5 trillion by 2027</span>
            </li>
            <li>22% of wellness growth is attributed to the spa segment</li>
            <li>
              Global day spa market expected to reach{" "}
              <span className="font-semibold">$57B by 2033</span>
            </li>
          </ul>
        </div>
      </section>

      {/* Location with JLL */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold mb-6">Finding Your Location</h2>
          <p className="max-w-3xl mx-auto mb-8">
            Finding a great location for your Spavia requires collaboration
            between the franchise partner, Spavia National, and our real estate
            partner, JLL.
          </p>
          <Image
            src="/your-spavia/JLL-logo.png"
            alt="JLL Logo"
            width={200}
            height={90}
            className="mx-auto"
          />
        </div>
      </section>

      {/* Image Carousel */}
      <section className="py-20 bg-white">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-center text-3xl md:text-4xl font-bold mb-3">
            Inside a Spavia
          </h2>
          <p className="text-center text-gray-600 mb-12 max-w-xl mx-auto">
            A look at the spaces, treatments, and details that make up the
            Spavia guest experience.
          </p>

          {/* Desktop — 3-col bento mosaic, hero top-left takes a 2x2 block */}
          <div className="hidden md:grid md:grid-cols-3 md:auto-rows-[260px] gap-4">
            <Reveal className="md:col-span-2 md:row-span-2 relative overflow-hidden rounded-xl shadow-md">
              <Image
                src={galleryImages[0].src}
                alt={galleryImages[0].alt}
                fill
                sizes="(max-width: 768px) 100vw, 66vw"
                className="object-cover"
              />
            </Reveal>
            {galleryImages.slice(1).map((img, i) => (
              <Reveal
                key={img.src}
                delay={(i + 1) * 60}
                className="relative overflow-hidden rounded-xl shadow-md"
              >
                <Image
                  src={img.src}
                  alt={img.alt}
                  fill
                  sizes="(max-width: 768px) 100vw, 33vw"
                  className="object-cover"
                />
              </Reveal>
            ))}
          </div>

          {/* Mobile — single-image carousel */}
          <div className="md:hidden relative w-full">
            <AnimatePresence mode="wait">
              <motion.div
                key={currentImageIndex}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.4 }}
                className="w-full"
              >
                <Image
                  src={galleryImages[currentImageIndex].src}
                  alt={galleryImages[currentImageIndex].alt}
                  width={1200}
                  height={800}
                  sizes="100vw"
                  className="rounded-xl shadow-md object-cover w-full aspect-[3/2]"
                />
              </motion.div>
            </AnimatePresence>

            <div className="flex justify-between items-center px-2 absolute inset-x-0 inset-y-0 pointer-events-none">
              <button
                onClick={prevImage}
                className="pointer-events-auto p-2 rounded-full bg-white/80 backdrop-blur-sm text-gray-800 hover:bg-white transition-colors active:scale-95"
                aria-label="Previous image"
              >
                <ChevronLeft size={24} />
              </button>
              <button
                onClick={nextImage}
                className="pointer-events-auto p-2 rounded-full bg-white/80 backdrop-blur-sm text-gray-800 hover:bg-white transition-colors active:scale-95"
                aria-label="Next image"
              >
                <ChevronRight size={24} />
              </button>
            </div>

            {/* Dot indicator */}
            <div className="flex justify-center gap-2 mt-4">
              {galleryImages.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setCurrentImageIndex(i)}
                  aria-label={`Go to image ${i + 1}`}
                  className={`h-1.5 rounded-full transition-all ${
                    i === currentImageIndex
                      ? "w-6 bg-[#C2A878]"
                      : "w-1.5 bg-gray-300"
                  }`}
                />
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Interactive Available Markets */}
      <section className="py-20 bg-gray-50 text-center">
        <h2 className="text-3xl font-bold mb-4">Available Markets</h2>
        <p className="mb-6 text-gray-700">
          {locationCounts.open} Spavias open across {locationCounts.states}{" "}
          states, with {locationCounts.comingSoon} more on the way. Click your
          state for additional territory information.
        </p>

        {/* Legend */}
        <div className="flex flex-wrap justify-center items-center gap-x-5 gap-y-2 mb-8">
          <div className="flex items-center space-x-2">
            <span
              className="w-4 h-4 rounded-full"
              style={{ backgroundColor: gold }}
            ></span>
            <span className="text-sm font-semibold">Available</span>
          </div>
          <div className="flex items-center space-x-2">
            <span
              className="w-4 h-4 rounded-full"
              style={{ backgroundColor: limited }}
            ></span>
            <span className="text-sm font-semibold">Limited Market</span>
          </div>
          <div className="flex items-center space-x-2">
            <span className="w-3 h-3 rounded-full bg-[#1a1a1a] ring-2 ring-white"></span>
            <span className="text-sm font-semibold">Spavia open</span>
          </div>
          <div className="flex items-center space-x-2">
            <span className="w-3 h-3 rounded-full bg-white border-2 border-[#1a1a1a]"></span>
            <span className="text-sm font-semibold">Opening soon</span>
          </div>
        </div>

        <div className="relative flex justify-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox={usa.viewBox}
            className="w-[960px] max-w-full"
            role="img"
            aria-label={`US map of available markets showing ${locationCounts.open} open Spavia locations`}
          >
            <title>
              US map of available markets with existing Spavia locations
            </title>
            {usa.locations.map((loc: Location) => {
              const name = (loc.name || loc.id || "").toString();
              const isLimited = limitedSet.has(name);
              const isHover = hoveredState === name;
              const fill = isHover ? hover : isLimited ? limited : gold;

              return (
                <path
                  key={loc.id}
                  d={loc.path}
                  fill={fill}
                  stroke="#FFFFFF"
                  strokeWidth={1}
                  className="cursor-pointer transition-colors duration-200"
                  onMouseEnter={() => setHoveredState(name)}
                  onMouseLeave={() => setHoveredState(null)}
                  onClick={() => setSelectedState(name)}
                  aria-label={name}
                />
              );
            })}

            {/* Existing Spavias, plotted from the corporate store locator */}
            <g>
              {plottable.map((loc) => {
                const isComingSoon = loc.status === "coming-soon";
                const isHovered = hoveredLocation?.id === loc.id;
                return (
                  <circle
                    key={loc.id}
                    cx={loc.x as number}
                    cy={loc.y as number}
                    r={isHovered ? 7 : 5}
                    fill={isComingSoon ? "#FFFFFF" : "#1a1a1a"}
                    stroke={isComingSoon ? "#1a1a1a" : "#FFFFFF"}
                    strokeWidth={2}
                    className="cursor-pointer transition-all duration-150"
                    onMouseEnter={() => {
                      setHoveredLocation(loc);
                      setHoveredState(loc.stateName);
                    }}
                    onMouseLeave={() => {
                      setHoveredLocation(null);
                      setHoveredState(null);
                    }}
                    onClick={() => setSelectedState(loc.stateName)}
                  >
                    <title>{`${loc.name} — ${loc.city}, ${loc.state}${
                      isComingSoon ? " (opening soon)" : ""
                    }`}</title>
                  </circle>
                );
              })}
            </g>
          </svg>

          {(hoveredLocation || hoveredState) && (
            <div className="absolute -bottom-8 left-1/2 -translate-x-1/2 bg-black text-white text-xs px-3 py-1 rounded shadow whitespace-nowrap">
              {hoveredLocation
                ? `${hoveredLocation.name} — ${hoveredLocation.city}, ${hoveredLocation.state}`
                : hoveredState}
            </div>
          )}
        </div>

        <p className="mt-6 text-sm text-gray-600">
          Limited markets: {limitedMarkets.join(", ")}.
        </p>
      </section>

      {/* Existing Spavia locations */}
      <section className="py-20 bg-white px-4 sm:px-6">
        <div className="max-w-6xl mx-auto">
          <Reveal>
            <h2 className="text-3xl font-bold text-center mb-4">
              Where You’ll Find Spavia
            </h2>
          </Reveal>
          <p className="text-center text-gray-700 max-w-2xl mx-auto mb-10">
            Every Spavia below is an operating location run by a franchise
            partner. Explore the markets we’re already in, and where we’re
            headed next.
          </p>

          <div className="grid grid-cols-3 gap-4 max-w-2xl mx-auto mb-12 text-center">
            {[
              { value: locationCounts.open, label: "Spavias open" },
              { value: locationCounts.comingSoon, label: "Opening soon" },
              { value: locationCounts.states, label: "States" },
            ].map((stat) => (
              <div key={stat.label} className="py-4">
                <div className="text-4xl font-bold text-[#C2A878]">
                  {stat.value}
                </div>
                <div className="text-sm text-gray-600 mt-1">{stat.label}</div>
              </div>
            ))}
          </div>

          <div className="columns-1 sm:columns-2 lg:columns-3 gap-8">
            {[...byStateName.entries()].map(([stateName, locs]) => (
              <div key={stateName} className="break-inside-avoid mb-8">
                <h3 className="font-bold text-gray-900 border-b border-[#C2A878] pb-1 mb-3">
                  {stateName}
                  <span className="text-gray-400 font-normal text-sm ml-2">
                    {locs.length}
                  </span>
                </h3>
                <ul className="space-y-2">
                  {locs.map((loc) => (
                    <li key={loc.id} className="text-sm leading-snug">
                      <a
                        href={loc.website}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="font-medium text-gray-900 hover:text-[#C2A878] transition-colors"
                      >
                        {loc.name}
                      </a>
                      <div className="text-gray-500">
                        {loc.city}, {loc.state}
                        {loc.status === "coming-soon" && (
                          <span className="ml-2 inline-block rounded-full border border-[#C2A878] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-[#C2A878]">
                            Opening soon
                          </span>
                        )}
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <p className="text-center text-xs text-gray-500 mt-8">
            Location list last updated {locationData.generatedAt}.
          </p>
        </div>
      </section>

      {/* Modal */}
      {selectedState && (
        <div className="fixed inset-0 flex items-center justify-center bg-black/60 z-50">
          <div
            className="bg-white max-w-lg w-full p-6 rounded-lg shadow-xl relative"
            role="dialog"
            aria-modal="true"
            aria-labelledby="stateDialogTitle"
          >
            <button
              className="absolute top-3 right-3 text-gray-500 hover:text-black"
              onClick={() => setSelectedState(null)}
              aria-label="Close dialog"
            >
              <X size={20} />
            </button>

            <h2 id="stateDialogTitle" className="text-xl font-bold mb-3">
              {selectedState}
            </h2>

            {selectedLocations.length > 0 && (
              <div className="mb-4">
                <p className="text-sm font-semibold text-gray-900 mb-2">
                  {selectedLocations.length}{" "}
                  {selectedLocations.length === 1 ? "Spavia" : "Spavias"} in{" "}
                  {selectedState}
                </p>
                <ul className="max-h-48 overflow-y-auto space-y-1 text-sm text-gray-700 pr-1">
                  {selectedLocations.map((loc) => (
                    <li key={loc.id} className="flex items-baseline gap-2">
                      <span
                        className={`mt-1.5 w-2 h-2 shrink-0 rounded-full ${
                          loc.status === "coming-soon"
                            ? "bg-white border border-[#1a1a1a]"
                            : "bg-[#1a1a1a]"
                        }`}
                      />
                      <span>
                        <a
                          href={loc.website}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="font-medium hover:text-[#C2A878] transition-colors"
                        >
                          {loc.name}
                        </a>{" "}
                        <span className="text-gray-500">
                          {loc.city}
                          {loc.status === "coming-soon" && " · opening soon"}
                        </span>
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <p className="mb-4 text-gray-700">
              Thank you for your interest in Spavia! We’re excited to share that
              we’re looking to grow in your state.
              <br />
              <br />
              To learn more, simply complete the contact form by clicking the
              button below, and our team will be in touch with you shortly.
            </p>
            <a
              href="/get-started"
              className="inline-block bg-black text-white px-5 py-2 rounded-full hover:bg-gray-800 transition"
            >
              Contact Us
            </a>
          </div>
        </div>
      )}

      {/* FAQ */}
      <section className="py-20 bg-white px-4 sm:px-6">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            {yourSpaviaFaqs.map((faq, index) => {
              const isOpen = openFaqIndex === index;
              return (
                <div key={index} className="border-b pb-4 transition-colors">
                  <button
                    onClick={() => setOpenFaqIndex(isOpen ? null : index)}
                    className="w-full text-left flex justify-between items-center font-semibold text-lg text-gray-900 hover:text-[#C2A878] transition-colors cursor-pointer"
                  >
                    {faq.question}
                    <span
                      className={`text-2xl font-bold transform transition-transform duration-300 ${
                        isOpen ? "rotate-180 text-[#C2A878]" : "rotate-0 text-gray-500"
                      }`}
                    >
                      {isOpen ? "\u2212" : "+"}
                    </span>
                  </button>
                  <div
                    className={`overflow-hidden transition-all duration-500 ease-in-out ${
                      isOpen ? "max-h-96 opacity-100 mt-3" : "max-h-0 opacity-0"
                    }`}
                  >
                    <p className="text-gray-700 leading-relaxed">{faq.answer}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Awards */}
      <section className="snap-start bg-gray-50">
        <AwardsSection />
      </section>

      {/* Next Page Link */}
      <div className="bg-black text-white py-10 text-center">
        <Link
          href="/steps-to-ownership"
          className="inline-block bg-[#C2A878] text-white px-6 py-3 rounded-lg font-semibold hover:bg-[#b09466] transition"
        >
          Next: Steps to Ownership →
        </Link>
      </div>

      <Footer />
    </main>
  );
}
